! WRITTEN BY VINEETH RAVI
! FOLLOWING IS A UMAT CODE FOR LAMINA
! VARIABLES FROM THE LETTER I TO N ARE CONSIDEREDED TO BE INTEGERS
! AND VARIABLES STARTING WITH OTHER LETTERS ARE DOUBLE PRECISION
! SO PLEASE BE CAREFUL IN NAMING THE VARIABLES
! EXAMPLES OF FEW DEFAULT INTEGERS : NTENS, NDI, NSHR
! EXAMPLES OF FEW DEFAULT REAL NUMBERS : DDSDDE, STRESS, STRAN
! THE KEYWORD *Transverse Shear Stiffness NEEDS TO ENTERED BEFORE CARRYING OUT THE SIMULATIONS
! MORE DETAILS CAN BE FOUND IN THE ABAQUS MANUAL
      
      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)

      INCLUDE 'ABA_PARAM.INC'

      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3),
     4 JSTEP(4)
      
      PARAMETER (ZERO = 0.0D0, ONE = 1.0D0, TWO = 2.0D0, FOUR = 4.0D0, PI = 3.14159265358979D0)
	 
      E11 = PROPS(1)    ! ELASTIC MODULUS IN THE LONGITUDINAL 1 DIRECTION
      E22 = PROPS(2)    ! ELASTIC MODULUS IN THE TRANSVERSE 2 DIRECTION
      PR12 = PROPS(3)   ! MAJOR POISSONS RATIO IN 1-2 PLANE
      G12 = PROPS(4)    ! SHEAR MODULUS IN 1-2 PLANE
      
      XT = PROPS(5)     ! LONGITUDINAL STRENGTH IN THE 1 DIRECTION
      XC = PROPS(6)     ! COMPRESSIVE STRENGTH IN THE 1 DIRECTION
      YT = PROPS(7)     ! LONGITUDINAL STRENGTH IN THE 2 DIRECTION
      YC = PROPS(8)     ! COMPRESSIVE STRENGTH IN THE 2 DIRECTION
      S = PROPS(9)      ! SHEAR STRENGTH IN THE 1-2 PLANE
      GIC = PROPS(10)   ! MODE I FRACTURE TOUGHNESS 
      GIIC = PROPS(10)  ! MODE II FRACTURE TOUGHNESS
      
      PR21 = (E22*PR12)/E11     ! CALCULAION OF MINOR POISSONS RATIO	   
		   
      DO I=1,NTENS  ! INITIALIZATION OF JACOBIAN MATRIX
          DO J=1,NTENS
              DDSDDE(I,J) = ZERO
          ENDDO
      ENDDO
	   
      DDSDDE(1,1) = E11/(1-PR12*PR21)
      DDSDDE(1,2) = PR12*E22/(1-PR12*PR21)
      DDSDDE(2,1) = PR12*E22/(1-PR12*PR21)
      DDSDDE(2,2) = E22/(1-PR12*PR21)
      DDSDDE(3,3) = G12
      
      DO I=1, NTENS
          DO J=1, NTENS
              STRESS(I) = STRESS(I) + DDSDDE(I, J)*DSTRAN(J) ! UPDATING STRESS TENSOR   
          END DO
      END DO
      
    
      STATEV = ZERO
      S11=STRESS(1)     ! NORMAL STRESS ALONG 1 DIRECTION
      S22=STRESS(2)     ! NORMAL STRESS ALONG 2 DIRECTION 
      S12=STRESS(3)     ! SHEAR STRESS IN 1-2 PLANE 
      
      ALPHA0 = 53*PI/180
      G = GIC/GIIC
      ETAL = -(S*COS(TWO*ALPHA0))/(YC*COS(ALPHA0)**2)
      PHIC = ATAN( (1-SQRT(1-FOUR*(S/XC + ETAL)*(S/XC)))/(TWO*(S/XC + ETAL)))
      
      S22M = S11*SIN(PHIC)**2 + S22*COS(PHIC)**2 - TWO*ABS(S12)*SIN(PHIC)*COS(PHIC)
      S12M = (S22 - S11)*SIN(PHIC)*COS(PHIC) + ABS(S12)*(COS(PHIC)**2 - SIN(PHIC)**2)
      
      THETA = ATAN(-ABS(S12)/(S22*SIN(ALPHA0)))
      ETAT = -ONE/TAN(TWO*ALPHA0)
      ST = YC*COS(ALPHA0)*(SIN(ALPHA0) +  COS(ALPHA0)/TAN(TWO*ALPHA0))
      TAUT = -S22*COS(ALPHA0)*(SIN(ALPHA0) - ETAT*COS(ALPHA0)*COS(THETA))
      TAUL = COS(ALPHA0)*(ABS(S12) + ETAL*S22*COS(ALPHA0)*SIN(THETA))
      
      
      IF ( S11 .GE. 0.0 ) THEN
          STATEV(1) = (S11 - PR12*S22)/XT                                  ! FIBER FAILURE IN TENSION 
      ELSE
          IF (ABS(S12M) + ETAL*S22M .GT. 0.0 ) THEN
              STATEV(2) = (ABS(S12M) + ETAL*S22M)/S                        ! FIBER FAILURE IN COMPRESSION
          END IF     
      END IF
      
      IF ( S22 .GE. 0.0 ) THEN
          STATEV(3) = SQRT((ONE - G)*S22/YT + G*(S22/YT)**2 + (S12/S)**2)  ! MATRIX FAILURE IN TENSION
      ELSE
          IF (ABS(S12) + ETAL*S22 .GT. 0.0 ) THEN
              STATEV(4) = (ABS(S12) + ETAL*S22)/S                          ! MATRIX FAILURE IN COMPRESSION WITH ALPHA0 = 0°
          ELSE
          IF (TUAT .LE. 0.0) THEN
              TUAT = ZERO
          END IF
          IF (TUAL .LE. 0.0) THEN
              TUAL = ZERO
          END IF
          STATEV(5) = SQRT((TAUT/ST)**2 + (TAUL/S)**2)                     ! MATRIX FAILURE IN COMPRESSION WITH ALPHA0 = 53°
          END IF 
      END IF
      
      
      RETURN
      END